[[UCX]]
arch = "powerpc64le"
git-tree-sha1 = "e0360aecf2a744452edf33ebf40ec921a897db53"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "f706fb35e5f864fd743154d65f59b8cca57a926eb256da89966c27c65f375819"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.7.0+2/UCX.v1.7.0.powerpc64le-linux-gnu.tar.gz"
[[UCX]]
arch = "x86_64"
git-tree-sha1 = "3e7b91104bff0b800e745b2ea692742e46cb2bc1"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "8dc31bf9be62d5f73256f5dbab5118e709a27ef2a8488129f6083913d470acd8"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.7.0+2/UCX.v1.7.0.x86_64-linux-gnu.tar.gz"
