[[UCX]]
arch = "aarch64"
git-tree-sha1 = "8f8b33178d0045113a718c5283bc09d1d44ed2fa"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "9b19b126461883f0bb565e40db574c4b61ffdb6c309ec19b4212ab70f49a8da4"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.18.0+0/UCX.v1.18.0.aarch64-linux-gnu.tar.gz"
[[UCX]]
arch = "powerpc64le"
git-tree-sha1 = "d5a477e7824376c17c2ee6425412b17da6e74ad2"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "0ac46d90524f40ae2c9b8d4e57f458c0f212de6aedf64d04ed550735a51d752f"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.18.0+0/UCX.v1.18.0.powerpc64le-linux-gnu.tar.gz"
[[UCX]]
arch = "x86_64"
git-tree-sha1 = "147deee9664c675769e6818f488fc6dbf9cc0b86"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "3fd5a84b695b954b32f9ca1e8974c3dfc9f84bd4b7761084841691b3edf81ac2"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.18.0+0/UCX.v1.18.0.x86_64-linux-gnu.tar.gz"
