[[UCX]]
arch = "powerpc64le"
git-tree-sha1 = "8a1effebab1b7f05ac5347a387324dc3d0c2ea64"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "25336716ff922604e995fde3303aaee52960c7cbb2c8001d3da52d49af376780"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.9.0+0/UCX.v1.9.0.powerpc64le-linux-gnu.tar.gz"
[[UCX]]
arch = "x86_64"
git-tree-sha1 = "e6bc58d16399ebcdd1a8d7635f49405dc128da28"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "12ef9a14337247764a99dbb8f1dd18b6b98b9072d8c737b8a363cd889aed08a0"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.9.0+0/UCX.v1.9.0.x86_64-linux-gnu.tar.gz"
