[[UCX]]
arch = "powerpc64le"
git-tree-sha1 = "1dab8eb7e90e7a6c846bcd5b2c8265003cbaef00"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "cad537f78daa22a77b51cb22bb778b86ea7665364e37ed98b211b690350dbaa3"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.7.0+0/UCX.v1.7.0.powerpc64le-linux-gnu.tar.gz"
[[UCX]]
arch = "x86_64"
git-tree-sha1 = "bbef9a25dcee2a91b2f66840adb324656a73c908"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "a8ceb0c781ec8d752aaa6c5987d896aa3cebcb97620a396bc94066e5934c94ff"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.7.0+0/UCX.v1.7.0.x86_64-linux-gnu.tar.gz"
