[[UCX]]
arch = "aarch64"
git-tree-sha1 = "c764e12540896034c600ad1c2721e3ac291e7385"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "7b2c4fa2c7b9b1a92662eb4d75119e780b3f9f816ed3267a191e529c7494fc32"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.10.0+1/UCX.v1.10.0.aarch64-linux-gnu.tar.gz"
[[UCX]]
arch = "powerpc64le"
git-tree-sha1 = "c562e02030f0ed03000e8554bb22700bfdf41994"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "4fe9db7781222f8f26cf79946b7ede152d2490fc42a0aed9117b0c7e2478cd93"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.10.0+1/UCX.v1.10.0.powerpc64le-linux-gnu.tar.gz"
[[UCX]]
arch = "x86_64"
git-tree-sha1 = "70accc3f45c57f86fa4f68a9a26d05f3762bee4d"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "1645c6070f57705743b1fc893d250827b30ef7f6af15f3beaaade0b507b10b36"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.10.0+1/UCX.v1.10.0.x86_64-linux-gnu.tar.gz"
