[[UCX]]
arch = "aarch64"
git-tree-sha1 = "29395952be80f1259ed9ffff66014a4be8a6e407"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "5707e504843aa787c7d20f45bd1c2cee0fefd050b72d1ce144543b37daa0c71b"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.10.0+0/UCX.v1.10.0.aarch64-linux-gnu.tar.gz"
[[UCX]]
arch = "powerpc64le"
git-tree-sha1 = "8b8c77d4af91977d64347f4d1dd0476c96f66e25"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "a8eba574583aa8643e1aebef79d51a34dcdc91cea946b73d031ddbe41cd3d871"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.10.0+0/UCX.v1.10.0.powerpc64le-linux-gnu.tar.gz"
[[UCX]]
arch = "x86_64"
git-tree-sha1 = "80f1f2b84b691daecdfb5a25ffdae431fd6ad5a1"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "ff04619c8bc86f55f9c2a58e45800759309d11b516f6a13045b30209f27b028b"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.10.0+0/UCX.v1.10.0.x86_64-linux-gnu.tar.gz"
