[[UCX]]
arch = "powerpc64le"
git-tree-sha1 = "e9c52c5241f8a149af4b66c0dd4fd331e28a5f68"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "07a9dc10d2fdec662e8dd030ae23122c043b6d4e6baa3be8693752288ff42afa"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.7.0+1/UCX.v1.7.0.powerpc64le-linux-gnu.tar.gz"
[[UCX]]
arch = "x86_64"
git-tree-sha1 = "d5d301e5c6064c3f05e8c7a3102e940d2d35e67f"
libc = "glibc"
os = "linux"

    [[UCX.download]]
    sha256 = "6f53b0dd4671f562905c4397b1b3b2cf72a073e78c28c1beec8da321d7ee3f67"
    url = "https://github.com/JuliaBinaryWrappers/UCX_jll.jl/releases/download/UCX-v1.7.0+1/UCX.v1.7.0.x86_64-linux-gnu.tar.gz"
