# Autogenerated wrapper script for UCX_jll for x86_64-linux-gnu
export libucm, libucp, libucs, libuct, ucx_info, ucx_perftest, ucx_read_profile

using CompilerSupportLibraries_jll
using NUMA_jll
using rdma_core_jll
JLLWrappers.@generate_wrapper_header("UCX")
JLLWrappers.@declare_library_product(libucm, "libucm.so.0")
JLLWrappers.@declare_library_product(libucp, "libucp.so.0")
JLLWrappers.@declare_library_product(libucs, "libucs.so.0")
JLLWrappers.@declare_library_product(libuct, "libuct.so.0")
JLLWrappers.@declare_executable_product(ucx_info)
JLLWrappers.@declare_executable_product(ucx_perftest)
JLLWrappers.@declare_executable_product(ucx_read_profile)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, NUMA_jll, rdma_core_jll)
    JLLWrappers.@init_library_product(
        libucm,
        "lib/libucm.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libucp,
        "lib/libucp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libucs,
        "lib/libucs.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libuct,
        "lib/libuct.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        ucx_info,
        "bin/ucx_info",
    )

    JLLWrappers.@init_executable_product(
        ucx_perftest,
        "bin/ucx_perftest",
    )

    JLLWrappers.@init_executable_product(
        ucx_read_profile,
        "bin/ucx_read_profile",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
